# Generated by Django 5.1.6 on 2025-06-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'author'], 'verbose_name': "User's post", 'verbose_name_plural': "User's posts"},
        ),
    ]
