# Generated by Django 5.1.6 on 2025-07-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contact_linked_user_message_delete_massage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_published',
        ),
    ]
