# Generated by Django 5.1.6 on 2025-07-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='caption',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
